services:
  - type: web
    name: meta_firma_api
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main
    autoDeploy: true
